### ISSUE TITLE
PrimeReact third party modules are not found

### ISSUE THREAD

**Issue by sudheerj** [primefaces/primereact-quickstart#3]
While running PrimeReact quickstart app some of the external third party dependency modules are not found.

For example, chart.js,jquery and fullcalendar modules

**Comment by mertsincan** [comment]
Hi @sudheerj,
For now, you can add the following dependencies into package.json;
```
"dependencies": {
    ....
    "chart.js": "^2.4.0",     
    "jquery": "^3.1.1",            
    "fullcalendar": "^3.1.0",    
    "moment": "^2.17.1"        /* for FullCalendar */
  },
```

I'll fix this issue for next version.
