### ISSUE TITLE
Failed to compile.

### ISSUE THREAD

**Issue by DerekLiang** [primefaces/primereact-quickstart#4]
I ran 
```
yarn
npm start
```

I go the following error.

```
Failed to compile.

Error in ./src/App.js
Module not found: 'primereact' in C:\src\primereact-quickstart\src

 @ ./src/App.js 14:18-39
```

Do I miss something?

**Comment by mertsincan** [comment]
Fixed now. Please try it after updating primereact-quickstart.
Regards,

**Comment by sudheerj** [comment]
Hi Mert,
           Is that issue fixed. I can replicate the issue now. Please let me know if i miss anything.Thanks.

**Comment by mertsincan** [comment]
Thanks @sudheerj, fixed now. Please try again.
