### ISSUE TITLE
Can't resolve 'chart.js/src/chart.js' in '....\primereact-quickstart-master\node_modules\primereact\components\chart'

### ISSUE THREAD

**Issue by ManikumarRavva** [primefaces/primereact-quickstart#6]
I am not able to import Chart from chart.js.....i used this below statement to import 
"import { Chart } from 'primereact/components/chart/Chart';"

While compiling i am getting below error 
"Can't resolve 'chart.js/src/chart.js' in '.......\primereact-quickstart-master\primereact-quickstart-master\node_modules\primereact\components\chart' "...can anyone help me out

**Comment by mertsincan** [comment]
Please add "chart.js": "2.7.1" to package.json.

**Comment by kluplau** [comment]
Shouldn't it be added to the dependencies on the Readme also? 

Currently says
```
dependencies: {
    "react": "^16.0.0",
    "react-dom": "^16.0.0",
    "react-transition-group": "^2.2.1",
    "classnames": "^2.2.5",
    "primeicons": "^1.0.0-beta.10"
}
```
